### ISSUE TITLE
Machine Learning 资源过期了

### ISSUE THREAD

**Issue by QingfengYang** [panyang/coursera-archive#2]
Hi 非常感谢你们提供的 课程存档，但是
Machine Learning by Pedro Domingos URL: http://pan.baidu.com/s/1gfx1GaB PASS: 6gee
这个课程下载不了呀。能给个新连接么，找了很久了没找到这个资源

**Comment by panyang** [comment]
主要是更新不就链接就被百度干掉了，实在没时间操作这个事情，近期可能会做一次更新，可以关注我们的公众号: NLPJob ，到时候会在上面推送
